// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUL7QhRlzDwZCOorWJUn50oxNIdodeXQ',
    appId: '1:127786404441:web:be1f42486757aec507bf48',
    messagingSenderId: '127786404441',
    projectId: 'flutter-phone-auth-30fea',
    authDomain: 'flutter-phone-auth-30fea.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-30fea.appspot.com',
    measurementId: 'G-TW1NMC8CHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1GrP5CGjy7PupQJOLmMyUenwYe0qkdo',
    appId: '1:127786404441:android:88dd90290059e44f07bf48',
    messagingSenderId: '127786404441',
    projectId: 'flutter-phone-auth-30fea',
    storageBucket: 'flutter-phone-auth-30fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3p47wA4uq-Qn26BViX3o0JF3FafqYKo0',
    appId: '1:127786404441:ios:be70388963bdff0b07bf48',
    messagingSenderId: '127786404441',
    projectId: 'flutter-phone-auth-30fea',
    storageBucket: 'flutter-phone-auth-30fea.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3p47wA4uq-Qn26BViX3o0JF3FafqYKo0',
    appId: '1:127786404441:ios:0792c57daf8d450107bf48',
    messagingSenderId: '127786404441',
    projectId: 'flutter-phone-auth-30fea',
    storageBucket: 'flutter-phone-auth-30fea.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
